/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sky.demo.thrift.common;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum UserType implements TEnum {
  ADMIN(1),
  AUDIT(2),
  COMMON(3);

  private final int value;

  private UserType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static UserType findByValue(int value) { 
    switch (value) {
      case 1:
        return ADMIN;
      case 2:
        return AUDIT;
      case 3:
        return COMMON;
      default:
        return null;
    }
  }
}
